name: BarBeeQ
options:
  bundleIdPrefix: com.barbeeq
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "16.2"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.20.2
  TCACoordinators:
    url: https://github.com/RomanPodymov/TCACoordinators.git
    version: 0.12.1
targets:
  BarBeeQApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [BarBeeQ]
    dependencies:
      - package: ComposableArchitecture
      - package: TCACoordinators
    info:
      path: BarBeeQ/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.5"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
