name: BarBeeQ
options:
  bundleIdPrefix: com.barbeeq
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "16.2"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.20.2
  TCACoordinators:
    url: https://github.com/johnpatrickmorgan/TCACoordinators.git
    version: 0.12.1
  FirebaseFirestore:
    url: https://github.com/firebase/firebase-ios-sdk.git
    version: 11.15.0
targets:
  BarBeeQApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ComposableArchitecture
      - package: TCACoordinators
      - package: FirebaseFirestore
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
  BarBeeQAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: BarBeeQApp
    info:
      path: Tests/Info.plist
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
