name: BarBeeQ
options:
  bundleIdPrefix: com.barbeeq
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "16.4"
packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture.git
    version: 1.22.1
  TCACoordinators:
    url: https://github.com/johnpatrickmorgan/TCACoordinators.git
    version: 0.13.0
  CombineFirebaseFirestore:
    url: https://github.com/RomanPodymov/CombineFirebase.git
    branch: master
  CombineFirebaseAuth:
    url: https://github.com/RomanPodymov/CombineFirebase.git
    branch: master
targets:
  BarBeeQApp:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: application
    platform: iOS
    sources: [Sources]
    dependencies:
      - package: ComposableArchitecture
      - package: TCACoordinators
      - package: CombineFirebaseFirestore
      - package: CombineFirebaseAuth
    info:
      path: Sources/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: YES
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
  BarBeeQAppTests:
    settings:
      base:
        SWIFT_VERSION: 6
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: ${SWIFT_ACTIVE_COMPILATION_CONDITIONS}
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: BarBeeQApp
    info:
      path: Tests/Info.plist
    postCompileScripts:
      - script: "/opt/homebrew/bin/mint run swiftformat . --swiftversion 5.9"
        name: SwiftFormat
      - script: "/opt/homebrew/bin/mint run swiftlint"
        name: SwiftLint
