name: BarBeeQJobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 16.2
      - name: Install Mint
        run: brew install mint
      - name: Generate Xcode project
        run: mint bootstrap && mint run xcodegen
      - name: Build and test iOS
        run: xcodebuild test -project BarBeeQ.xcodeproj -scheme BarBeeQApp -destination "platform=iOS Simulator,OS=18,name=iPhone 16" -skipMacroValidation
